version: 0.0
os: linux
files:
  - source: webapp.war
    destination: /var/lib/tomcat9/webapps/
    permissions:
   - object: /var/lib/tomcat9/webapps/
     pattern: "***"
     owner: tomcat
     group: tomcat
     mode: 755
     type:
       - file
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
 
